version: '3.7'

services:
  server:
    image: elvinfeng/portfolio:server
    container_name: portfolio-server
    restart: always
    build:
      context: ./api
    command: npm start
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`server.elvinfeng.com`) 
      - traefik.http.routers.server.tls=true
      - traefik.http.routers.server.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - traefik_web
  client:
    image: elvinfeng/portfolio:client
    container_name: portfolio-client
    restart: always
    build:
      context: ./client
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`elvinfeng.com`) 
      - traefik.http.routers.client.tls=true
      - traefik.http.routers.client.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - traefik_web
    depends_on:
      - server

networks:
  traefik_web:
    external: true
  internal:
    external: false