version: '3.7'

services:
  api:
    container_name: docker-api
    restart: always
    build: ./api
    command: npm start
    ports:
      - '5000:5000'
  client:
    container_name: docker-client
    restart: always
    build:
      context: ./client
    ports:
      - '8080:8080'
    depends_on:
      - api