version: '3.7'

services:
  server:
    container_name: portfolio-server
    restart: always
    build: ./api
    command: npm start
    ports:
      - '5000:5000'
  client:
    container_name: portfolio-client
    restart: always
    build:
      context: ./client
    ports:
      - '8080:8080'
    depends_on:
      - server